repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
        exclude: ^(data/manifests/|docs/figures/|results/|runs/)
      - id: trailing-whitespace
        exclude: ^(data/manifests/|docs/figures/|results/|runs/)
